version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-debug"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1jxiqca5k44rj"
s3_prefix = "sam-app-debug"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
